name: deploy 

on: 
  push: 
    branches: (master)  # master 分支有 push 时触发 

paths-ignore:  # 下列文件的变更不触发部署，可以自行添加
  - readme.md 

jobs: 
  deploy: 
    runs-on: ubuntu-latest 
    steps: 
      # 下载源码，检出你的仓库并下载里面的代码到 runner 中
      - name: checkout 
        uses: actions/checkout@v2 
      # 打包构建
      - name: build 
        uses: actions/setup-node@master 
        with: 
          node-version: '16.x' 
        run: npm install  # 安装依赖
        run: npm run build  # 打包
      # 部署到 github pages
      - name: deploy 
        uses: peaceiris/actions-gh-pages@v3 
        with: 
          publish_dir:./dist  # 部署打包后的 dist 目录
          github_token: ${{ secrets.deploy_secret }}  # secret 名
          user_name: ${{ secrets.my_user_name }} 
          user_email: ${{ secrets.my_user_email }} 
          commit_message: 自动部署  # 部署时的 git 提交信息，自由填写
